apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: wargaku
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false
        jsonData:
          httpMethod: POST
          timeInterval: "15s"

  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: EstateHub
        orgId: 1
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true
